apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivenews-backend
  namespace: hivenews
  labels:
    app: hivenews-backend
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hivenews-backend
  template:
    metadata:
      labels:
        app: hivenews-backend
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: backend
          image: ghcr.io/hivenews/backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: database_url
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: deepseek_api_key
            - name: VECTORIZER_URL
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: vectorizer_url
            - name: VECTORIZER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: vectorizer_api_key
            - name: SYNAP_URL
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: synap_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: hivenews-secrets
                  key: redis_url
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivenews-frontend
  namespace: hivenews
  labels:
    app: hivenews-frontend
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hivenews-frontend
  template:
    metadata:
      labels:
        app: hivenews-frontend
        version: v1.0.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: frontend
          image: ghcr.io/hivenews/frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
