# AIResearch Portal Configuration
# Format: YAML 1.2

portal:
  id: airesearch
  name: AIResearch
  domain: airesearch.news
  description: "Notícias científicas sobre Inteligência Artificial"

editorial:
  style: scientific
  cadence: "0 * * * *"  # 1 article per hour
  
  language:
    base: en
    translate_to:
      - pt-BR
      - es-ES
    min_rank_to_translate: 0.7
  
  image:
    style: "scientific, technical, clean, modern, professional"
    cover_aspect_ratio: "16:9"
    thumbnail_aspect_ratio: "1:1"
  
  seo:
    priority: high
    keywords:
      - artificial intelligence
      - machine learning
      - deep learning
      - LLMs
      - computer vision
      - NLP
      - AI research
      - robotics
      - neural networks

sources:
  # RSS Feeds (for metadata only)
  - url: https://arxiv.org/list/cs.AI/recent
    type: rss
    enabled: true
    refresh: "*/15 * * * *"  # Every 15 minutes
  
  - url: https://arxiv.org/list/cs.CV/recent
    type: rss
    enabled: true
    refresh: "*/15 * * * *"
  
  - url: https://arxiv.org/list/cs.LG/recent
    type: rss
    enabled: true
    refresh: "*/15 * * * *"
  
  # ArXiv API (for fetching full PDFs)
  - url: https://export.arxiv.org/api/query
    type: api
    enabled: true
    refresh: "0 * * * *"  # Every hour
    params:
      search_query: "cat:cs.AI OR cat:cs.CV OR cat:cs.LG"
      start: 0
      max_results: 25
      sortBy: "submittedDate"
      sortOrder: "descending"
    
  # BioRxiv API (biological sciences papers)
  - url: https://api.biorxiv.org/details/biorxiv
    type: api
    enabled: true
    refresh: "0 * * * *"
    params:
      server: biorxiv
      page: 0
      limit: 25
      sort: "date"
      order: "desc"
    
  # medRxiv API (medical papers)
  - url: https://api.biorxiv.org/details/medrxiv
    type: api
    enabled: true
    refresh: "0 * * * *"
    params:
      server: medrxiv
      page: 0
      limit: 25
      sort: "date"
      order: "desc"

publishing:
  schedule:
    frequency: hourly
    start_time: "00:00"
    timezone: "UTC"
  
  channels:
    - website
    - rss_feed
  
  post_format:
    include_cover_image: true
    include_schema_markup: true
    include_hreflang: true

quality:
  min_score: 0.7
  fact_check: true
  sources_required: 3
  expert_review: false

# CMMV Integration
cmmv:
  contract_namespace: "Editorial"
  auto_generate:
    - entities
    - controllers
    - rest_endpoints
    - rpc_methods



