# ScienceAI Portal Configuration
# Format: YAML 1.2

portal:
  id: scienceai
  name: Science AI
  domain: scienceai.news
  description: "AI News for Scientific Community"

editorial:
  style: scientific
  cadence: "0 * * * *"  # 1 article per hour
  
  language:
    base: en
    translate_to:
      - pt-BR
      - es-ES
    min_rank_to_translate: 0.7
  
  image:
    style: "scientific, educational, vibrant, modern, engaging"
    cover_aspect_ratio: "16:9"
    thumbnail_aspect_ratio: "1:1"
  
  seo:
    priority: high
    keywords:
      - AI science
      - research breakthrough
      - scientific AI
      - machine learning
      - AI applications
      - scientific computing
      - AI algorithms
      - data science

sources:
  - url: https://science.org/rss
    type: rss
    enabled: true
    refresh: "*/15 * * * *"
  
  - url: https://www.nature.com/feeds/machine-learning/topic.rss
    type: rss
    enabled: true
    refresh: "*/30 * * * *"

publishing:
  schedule:
    frequency: hourly
    start_time: "00:00"
    timezone: "UTC"
  
  channels:
    - website
    - rss_feed
  
  post_format:
    include_cover_image: true
    include_schema_markup: true
    include_hreflang: true

quality:
  min_score: 0.7
  fact_check: true
  sources_required: 3
  expert_review: false

# CMMV Integration
cmmv:
  contract_namespace: "Editorial"
  auto_generate:
    - entities
    - controllers
    - rest_endpoints
    - rpc_methods


